trigger:
    batch: true
    branches:
        include:
            - '*'
    tags:
        include:
            - '*'
pr:
    branches:
        include:
            - '*'

jobs:
    - job: Build
      displayName: 'Build'

      strategy:
          matrix:
              Development:
                  BuildConfiguration: development
              Production:
                  BuildConfiguration: production

      pool:
          vmImage: 'ubuntu-latest'

      steps:
          - task: NodeTool@0
            displayName: 'Install Node'
            inputs:
                versionSpec: '12.x'

          - task: Cache@2
            displayName: 'Check Cache'
            inputs:
                key: 'npm | package-lock.json'
                path: 'node_modules'
                cacheHitVar: CACHE_RESTORED

          - script: 'npm ci --no-audit'
            displayName: 'Install Dependencies'
            condition: ne(variables.CACHE_RESTORED, 'true')

          - script: 'sh ./scripts/updateversion.sh'
            displayName: 'Update version in package.json'

          - script: 'npm run build:development'
            displayName: 'Build Development'
            condition: eq(variables['BuildConfiguration'], 'development')

          - script: 'npm run build:production'
            displayName: 'Build Bundle'
            condition: eq(variables['BuildConfiguration'], 'production')

          - script: 'test -d dist'
            displayName: 'Check Build'

          - script: 'mv dist jellyfin-chromecast'
            displayName: 'Rename Directory'

          - task: ArchiveFiles@2
            displayName: 'Archive Directory'
            inputs:
                rootFolderOrFile: 'jellyfin-chromecast'
                includeRootFolder: true
                archiveFile: 'jellyfin-chromecast-$(BuildConfiguration)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Release'
            inputs:
                targetPath: '$(Build.SourcesDirectory)/jellyfin-chromecast-$(BuildConfiguration).zip'
                artifactName: 'jellyfin-chromecast-$(BuildConfiguration)'